services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - /Users/johnnymosby/data/wordpress:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      secrets:
        - wp_admin_password
        - wp_user_password
        - db_user_password
    env_file: .env
    networks:
      - inception
    ports:
      - 9000:9000
    volumes:
      - /Users/johnnymosby/data/wordpress:/var/www/html
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_user_password
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    networks:
      - inception
    ports:
      - 3306:3306
    volumes:
      - /Users/johnnymosby/data/mariadb:/var/lib/mysql
    secrets:
      - db_root_password
      - db_user_password
    restart: always


networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/johnnymosby/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/johnnymosby/data/wordpress
      o: bind

secrets:
  wp_admin_password:
    file: ../secrets/wordpress_admin_password.txt
  wp_user_password:
    file: ../secrets/wordpress_user_password.txt
  db_root_password:
    file: ../secrets/mariadb_root_password.txt
  db_user_password:
    file: ../secrets/mariadb_user_password.txt
